apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: quay.io/rhn_support_satripat/python-header-testing:v3
        name: python
        ports:
        - containerPort: 8000
          name: http
        imagePullPolicy: Always



oc expose deployment pyhon
oc expose svc python

x-forwarded chack client ip application
