prod-dc-istio-system                                              Active
[osuser@dcepayprodbastion ~]$ oc get route -n prod-dc-istio-system -o yaml
apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "4"
      meta.helm.sh/release-name: epay-common
      meta.helm.sh/release-namespace: prod-dc-epay-common
    creationTimestamp: "2025-12-30T14:57:36Z"
    labels:
      app: prod-dc-istio-gateway
      app.kubernetes.io/instance: epay-common
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prod-dc-istio-gateway-route
      environment: prod-dc
    name: prod-dc-istio-gateway-route
    namespace: prod-dc-istio-system
    resourceVersion: "644109187"
    uid: b3b926f2-45d5-4ad3-be29-f393bbfbb69b
  spec:
    host: sbiepay.sbi.bank.in
    port:
      targetPort: http2
    tls:
      insecureEdgeTerminationPolicy: None
      termination: edge
    to:
      kind: Service
      name: prod-dc-istio-gateway-service
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: "2025-12-30T14:57:36Z"
        status: "True"
        type: Admitted
      host: sbiepay.sbi.bank.in
      routerCanonicalHostname: router-default.apps.dc.prod.epay.sbi
      routerName: default
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
